### PR TITLE
Add message reply type to the filter

### PR DESCRIPTION
**Pull request by notsapinho**

### CODE REVIEW

**Comment by slow** [comment]
What message type is this if i may ask?

**Comment by notsapinho** [comment]
19

**Comment by slow** [comment]
Which corresponds to what

**Comment by notsapinho** [comment]
a message reply lol

**Comment by notsapinho** [comment]
image
```json
{
        "id": "856276575837093938",
        "type": 19,
        "content": "lol",
        "channel_id": "842389899188764673",
        "author": {
          "id": "693288915427262585",
          "username": "notsapinho",
          "avatar": "a_f21e30ccf2177a4e57e48d1929b2d42f",
          "discriminator": "2975",
          "public_flags": 131200
        },
        "attachments": [],
        "embeds": [],
        "mentions": [],
        "mention_roles": [],
        "pinned": false,
        "mention_everyone": false,
        "tts": false,
        "timestamp": "2021-06-20T20:57:24.529000+00:00",
        "edited_timestamp": null,
        "flags": 0,
        "components": [],
        "message_reference": {
          "channel_id": "842389899188764673",
          "guild_id": "762512071283048500",
          "message_id": "856276554664771664"
        },
        "hit": true
}
```

**Comment by slow** [comment]
Why would you not delete a reply though

**Comment by slow** [comment]
Add an option in settings for this since i doubt everyone wants to keep replies

**Comment by notsapinho** [comment]
im saying that is not deleting replies

**Comment by notsapinho** [comment]
b3H5mZyp2H

**Comment by notsapinho** [comment]
now if u add `|| msg.type === 19` to the filter it works

**Comment by slow** [comment]
https://media.wtf/18920863.mp4

**Comment by slow** [comment]
it works for me?

**Comment by slow** [comment]
what canary build are you on?

**Comment by notsapinho** [comment]
wtf

**Comment by notsapinho** [comment]
1 sec

**Comment by notsapinho** [comment]
ok somehow the code that i was using was fucked, so everything is fine. sorry for bothering lol

**Comment by slow** [comment]
don't worry about it

**Pull request closed without merging**
